//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crafty.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart_tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cart_tbl()
        {
            this.Order_tbl = new HashSet<Order_tbl>();
            this.Payment_tbl = new HashSet<Payment_tbl>();
        }
    
        public int Cart_ID { get; set; }
        public Nullable<int> P_ID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> Total_Price { get; set; }
        public Nullable<int> U_ID { get; set; }
    
        public virtual Product_tbl Product_tbl { get; set; }
        public virtual User_tbl User_tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_tbl> Order_tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment_tbl> Payment_tbl { get; set; }
    }
    public class CartProduct
    {

        public Cart_tbl cart { get; set; }
        public Product_tbl product { get; set; }



    }
}
