//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crafty.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_tbl
    {
        public int Order_ID { get; set; }
        public Nullable<System.DateTime> Order_Date { get; set; }
        public Nullable<int> Total { get; set; }
        public string Order_Status { get; set; }
        public Nullable<int> U_ID { get; set; }
        public Nullable<int> P_ID { get; set; }
        public Nullable<int> Cart_ID { get; set; }
        public Nullable<int> Pay_ID { get; set; }
    
        public virtual Cart_tbl Cart_tbl { get; set; }
        public virtual Product_tbl Product_tbl { get; set; }
        public virtual Payment_tbl Payment_tbl { get; set; }
        public virtual User_tbl User_tbl { get; set; }
    }
}
