//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crafty.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment_tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Payment_tbl()
        {
            this.Order_tbl = new HashSet<Order_tbl>();
        }
    
        public int Pay_ID { get; set; }
        public string Pay_Method { get; set; }
        public Nullable<int> Bkash_Number { get; set; }
        public Nullable<int> Transaction_ID { get; set; }
        public Nullable<System.DateTime> Pay_Date { get; set; }
        public string Pay_Status { get; set; }
        public Nullable<int> Pay_Amount { get; set; }
        public Nullable<int> Cart_ID { get; set; }
        public Nullable<int> P_ID { get; set; }
        public Nullable<int> U_ID { get; set; }
    
        public virtual Cart_tbl Cart_tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_tbl> Order_tbl { get; set; }
        public virtual Product_tbl Product_tbl { get; set; }
        public virtual User_tbl User_tbl { get; set; }
    }
}
