//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crafty.Models
{
    using System;
    using System.Web;
    using System.Collections.Generic;
    
    public partial class Product_tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product_tbl()
        {
            this.Cart_tbl = new HashSet<Cart_tbl>();
            this.Order_tbl = new HashSet<Order_tbl>();
            this.Payment_tbl = new HashSet<Payment_tbl>();
        }
    
        public int P_ID { get; set; }
        public string Product_Name { get; set; }
        public string Product_Image { get; set; }
        public string Product_Base_Price { get; set; }
        public string Product_Offer_Price { get; set; }
        public string Product_Discount { get; set; }
        public string Category { get; set; }
        public string Features { get; set; }
        public string Product_Descriptation { get; set; }
        public int Product_Stock { get; set; }
        public int Product_Sold { get; set; }
        public HttpPostedFileBase ImageFile { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cart_tbl> Cart_tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_tbl> Order_tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment_tbl> Payment_tbl { get; set; }
    }
}
